### ISSUE TITLE
The loss was always 0 when I was training on Task 2

### ISSUE THREAD

**Issue by jiangf8686** [DCASE-REPO/dcase2018_baseline#13]
The loss was always 0 when I was training on Task 2, and then I had this problem when I verified the effect.

NotFoundError (see above for traceback): Tensor name "Conv/biases" not found in checkpoint files /model.ckpt-14255.index
 [[Node: save/RestoreV2 = RestoreV2[dtypes=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_INT32], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2/tensor_names, save/RestoreV2/shape_and_slices)]]

**Comment by FunkMonkey** [comment]
I am experiencing the same on Windows. @jiangf8686 Did you find a solution?
