### ISSUE TITLE
task1 tensorflow-gpu in windows 10 has errors

### ISSUE THREAD

**Issue by jlch5555** [DCASE-REPO/dcase2018_baseline#14]
Environment : win10 64bit VS2013+CUDA9.0 +CuDNN9.0 keras2.2.0 and tensorflow-gpu 1.8, GTX960M 2g
run python task1a.py 
feature extraction, till collecting train and validation data are all right.
however, it report an error: Shape must be rank 1 but is rank 4 for 'batch_normalization_1/cond/FusedBatchNorm' (op: 'FusedBatchNorm') with input shapes: [?,40,500,32], [1,40,1,1], [1,40,1,1], [1,40,1,1], [1,40,1,1].
That means the output shape of Conv2D is rank4 rather than rank1. 
However, if I run it using CPU, this do not have this error. Does anyone know why?

**Comment by toni-heittola** [comment]
I do not have Windows 10 installation to recreate this issue. It seems that there has been some problems with batch_normalization layer with Keras / TensorFlow before, you could try proposed workaround from here > https://github.com/keras-team/keras/issues/4623#issuecomment-269125127

I have used keras 2.1.6 and tensorflow-gpu 1.7.0 version combination without any such problem during the system development.
