### ISSUE TITLE
task4:This video is unavailable.(deleted by user)

### ISSUE THREAD

**Issue by Kikyo-16** [DCASE-REPO/dcase2018_baseline#15]
when using code to download data from Youtube, I found that part of dataset had been deleted by users. How can I find them?

**Comment by rserizel** [comment]
Thanks for your interest in task 4.

As explained in the dataset [readme](https://github.com/DCASE-REPO/dcase2018_baseline/blob/master/task4/dataset/readme.md):

"The script produces missing_files[dataset].csv log files (were [dataset] corresponds to the name of a particular set) with a list of audio files that were not downloaded by the script. After completion if some of the files where not downloaded you might want to run the script a second to download missing files. If you are experiencing problems downloading the full dataset please contact the task organizers (see also task 4 official page)"

If you send these files to us (Nicolas Turpault or Romain Serizel), we'll take care of providing the missing audio files.

**Comment by Kikyo-16** [comment]
Hello , I am experiencing problems downloading the full dataset (some eval files are missing) , can you provide them ?
