### ISSUE TITLE
task 4: When trying to download data ImportError: numpy.core.multiarray failed to import

### ISSUE THREAD

**Issue by shairoz** [DCASE-REPO/dcase2018_baseline#2]
After installing the conda virtual env via conda_create_environment.sh script, virtual env successfully created.
When trying to download data:

Traceback (most recent call last):
  File "download_data.py", line 11, in <module>
    from dcase_util.containers import AudioContainer
...
    from numba import _dynfunc, _helperlib
ImportError: numpy.core.multiarray failed to import

could some dependencies be missing?

Ubuntu 16.04
Anaconda python 3.6 (virtualenv installed via script is   python 3.5)

Thanks

**Comment by turpaultn** [comment]
Could you please provide your "pip list" and "conda list" outputs ?

I do not succeed to reproduce the error.

Does your dcase_util version is 0.1.9 ?

**Comment by shairoz** [comment]
Yes, my dcase_util is 0.1.9

pip list 
audioread (2.1.4)
bleach (1.5.0)
certifi (2018.1.18)
cffi (1.11.5)
chardet (3.0.4)
colorama (0.3.9)
cycler (0.10.0)
dcase-util (0.1.9)
decorator (4.3.0)
enum34 (1.1.6)
future (0.16.0)
html5lib (0.9999999)
idna (2.6)
joblib (0.11)
kiwisolver (1.0.1)
librosa (0.6.0)
llvmlite (0.22.0)
Markdown (2.6.9)
matplotlib (2.2.2)
mkl-fft (1.0.0)
mkl-random (1.0.1)
msgpack-python (0.5.6)
numba (0.37.0)
numpy (1.13.3)
pafy (0.5.4)
pip (9.0.3)
protobuf (3.5.0.post1)
pycparser (2.18)
pydot-ng (1.0.0)
pyparsing (2.2.0)
python-dateutil (2.7.2)
python-magic (0.4.15)
pytz (2018.4)
PyYAML (3.12)
requests (2.18.4)
resampy (0.2.0)
scikit-learn (0.19.1)
scipy (1.0.1)
setuptools (38.2.4)
six (1.11.0)
SoundFile (0.10.1)
tensorflow-gpu (1.4.0)
tensorflow-tensorboard (0.4.0rc3)
titlecase (0.12.0)
tornado (5.0.2)
tqdm (4.23.0)
ujson (1.35)
urllib3 (1.22)
validators (0.12.1)
Werkzeug (0.12.2)
wheel (0.30.0)
youtube-dl (2018.4.16)

conda list

#
audioread                 2.1.4                    py35_1    conda-forge
bzip2                     1.0.6                         1    conda-forge
ca-certificates           2018.03.07                    0  
certifi                   2018.1.18                py35_0    conda-forge
cffi                      1.11.5                    <pip>
chardet                   3.0.4                     <pip>
colorama                  0.3.9                     <pip>
cycler                    0.10.0                   py35_0    conda-forge
dbus                      1.10.22                       0    conda-forge
dcase-util                0.1.9                     <pip>
decorator                 4.3.0                      py_0    conda-forge
decorator                 4.3.0                     <pip>
expat                     2.2.5                         0    conda-forge
ffmpeg                    3.4.2                         0    conda-forge
fontconfig                2.13.0                        0    conda-forge
freetype                  2.8.1                         0    conda-forge
future                    0.16.0                    <pip>
glib                      2.53.6               h5d9569c_2  
gmp                       6.1.2                         0    conda-forge
gnutls                    3.5.17                        0    conda-forge
gst-plugins-base          1.12.4               h33fb286_0  
gstreamer                 1.12.4               hb53b477_0  
icu                       58.2                          0    conda-forge
idna                      2.6                       <pip>
intel-openmp              2018.0.0                      8  
joblib                    0.11                     py35_0    conda-forge
jpeg                      9b                            2    conda-forge
kiwisolver                1.0.1                    py35_1    conda-forge
libedit                   3.1                  heed3624_0  
libffi                    3.2.1                hd88cf55_4  
libgcc                    7.2.0                h69d50b8_2  
libgcc-ng                 7.2.0                hdf63c60_3  
libgfortran-ng            7.2.0                hdf63c60_3  
libiconv                  1.15                          0    conda-forge
libidn11                  1.33                          0    conda-forge
libpng                    1.6.34                        0    conda-forge
librosa                   0.6.0                    py35_0    conda-forge
libstdcxx-ng              7.2.0                hdf63c60_3  
libuuid                   1.0.3                         1    conda-forge
libxcb                    1.13                          0    conda-forge
libxml2                   2.9.8                         0    conda-forge
llvmlite                  0.22.0                   py35_0    conda-forge
matplotlib                2.2.2                    py35_1    conda-forge
mkl                       2018.0.2                      1  
mkl_fft                   1.0.1                    py35_1    conda-forge
mkl_random                1.0.1                    py35_0    conda-forge
msgpack-python            0.5.6                     <pip>
ncurses                   6.0                  h9df7e31_2  
nettle                    3.3                           0    conda-forge
numba                     0.37.0          np114py35h095f75c_0  
numpy                     1.14.2           py35hdbf6ddf_1  
openssl                   1.0.2o               h20670df_0  
pafy                      0.5.4                     <pip>
pcre                      8.41                          1    conda-forge
pip                       9.0.3                    py35_0    conda-forge
pycparser                 2.18                      <pip>
pydot-ng                  1.0.0                     <pip>
pyparsing                 2.2.0                    py35_0    conda-forge
pyqt                      5.6.0                    py35_5    conda-forge
python                    3.5.5                hc3d631a_1  
python-dateutil           2.7.2                      py_0    conda-forge
python-dateutil           2.7.2                     <pip>
python-magic              0.4.15                    <pip>
pytz                      2018.4                     py_0    conda-forge
pytz                      2018.4                    <pip>
PyYAML                    3.12                      <pip>
qt                        5.6.2               h974d657_12  
readline                  7.0                  ha6073c6_4  
requests                  2.18.4                    <pip>
resampy                   0.2.0                    py35_1    conda-forge
scikit-learn              0.19.1           py35hbf1f462_0  
scipy                     1.0.1            py35hfc37229_0  
setuptools                39.0.1                   py35_0    conda-forge
sip                       4.18                     py35_1    conda-forge
six                       1.11.0                   py35_1    conda-forge
SoundFile                 0.10.1                    <pip>
sqlite                    3.22.0               h1bed415_0  
titlecase                 0.12.0                    <pip>
tk                        8.6.7                hc745277_3  
tornado                   5.0.2                    py35_0    conda-forge
tqdm                      4.23.0                    <pip>
tqdm                      4.22.0                     py_0    conda-forge
ujson                     1.35                      <pip>
urllib3                   1.22                      <pip>
validators                0.12.1                    <pip>
wheel                     0.31.0                   py35_0    conda-forge
x264                      20131217                      3    conda-forge
xorg-libxau               1.0.8                         3    conda-forge
xorg-libxdmcp             1.1.2                         3    conda-forge
xz                        5.2.3                h55aa19d_2  
youtube-dl                2018.4.16                 <pip>
zlib                      1.2.11               ha838bed_2

**Comment by turpaultn** [comment]
I think I found your problem: 
https://github.com/tensorflow/tensorflow/issues/559

In your pip list, you have numpy=numpy (1.13.3)
And in your conda list you have: numpy=numpy 1.14.2 py35hdbf6ddf_1

It means that 1.13.3 and 1.14.2 should be in conflict. 

Trying to reproduce your problem, I also have numpy from conda and pip, but they are at the same version (1.14.2).

**Comment by shairoz** [comment]
Updated the numpy to 1.14.2 and installed pandas (wasn't installed during env building script)
Works properly for now.
thanks

**Comment by turpaultn** [comment]
Perfect.
Yes sorry, I updated to add pandas I just saw it was missing when experimenting your problem.
