### ISSUE TITLE
Where to get labels of evaluation dataset?

### ISSUE THREAD

**Issue by GilgameshD** [DCASE-REPO/dcase2018_baseline#20]
As the competition has finished, where can I find the labels of evaluation dataset?
I hope to use this dataset in my research work.

Thanks a lot !

**Comment by toni-heittola** [comment]
Which task you are referring to?

Tasks 2, 4 and 5 have released reference annotations for evaluation dataset. For task 1, there is no plan of releasing the reference labels for evaluation or public leaderboard datasets (see http://dcase.community/challenge2018/task-acoustic-scene-classification#reference-labels).

**Comment by danstowell** [comment]
FYI task 3 does not currently plan to release the eval labels.

**Comment by GilgameshD** [comment]
Thanks for your reply.
