### ISSUE TITLE
[Task 4 - Baseline] YU5udL6UCigk_100.000_110.000.wav list index out of range

### ISSUE THREAD

**Issue by janaal1** [DCASE-REPO/dcase2018_baseline#22]
Hi everybody,

I am trying to run the baseline model and I get the following error when executing **DCASE2018_Task4_DevelopmentSet**. 

I get the following message:

check files exist or download data
100%|██████████| 71/71 [00:19<00:00,  3.66it/s]
100%|██████████| 616/616 [02:15<00:00,  4.55it/s]
100%|██████████| 13/13 [00:06<00:00,  1.92it/s]
100%|██████████| 1094/1094 [04:04<00:00,  4.47it/s]
  0%|          | 0/51 [00:00<?, ?it/s]YU5udL6UCigk_100.000_110.000.wav
list index out of range
100%|██████████| 51/51 [00:13<00:00,  3.69it/s]
[I]   DONE  

I am able to download 829 files in test folder....

dcase_util version: 0.2.5

**Comment by turpaultn** [comment]
The baseline cannot run with dcase_util version: 0.2.5, so you need to downgrade to dcase_util version: 0.2.4. 
However, this shoudn't be the problem, do you have more details about when this happen ?
It is normal that you can't download all the files, you'll have to send me a mail for the data you couldn't download.
