### ISSUE TITLE
Task1 error

### ISSUE THREAD

**Issue by Marinarg** [DCASE-REPO/dcase2018_baseline#24]
Hello, 

I'm running task1 baseline system for my study and I'm having an error:

"Shape must be rank 1 but is rank 0 for 'batch_normalization_1/cond/Reshape_4' (op: 'Reshape') with input shapes: [1,40,1,1], []."

This message appears when I try to create the sequential model with dcase_util.keras.create_sequential_model().
I have no idea what I should do.

**Comment by toni-heittola** [comment]
What version of Python, Keras and Tensorflow you are using? 

Provided baseline system has been tested only with versions defined in the https://github.com/DCASE-REPO/dcase2018_baseline/blob/master/task1/requirements.txt
