### ISSUE TITLE
Videos for these audios?

### ISSUE THREAD

**Issue by HarshVardhanSh** [DCASE-REPO/dcase2018_baseline#27]
I want to access the videos associated with these audios. I used the VideoIDs from these audio filenames but youtube says " the video is unavailable". Please help. Thanks

**Comment by HarshVardhanSh** [comment]
Nobody has not yet commented on this thread.

**Comment by turpaultn** [comment]
Some of the videos are now unavailable on youtube so it is impossible to get the video associated.

**Comment by HarshVardhanSh** [comment]
I guess all of the videos for weakly labelled audios are unavailable. BTW thanks for the confirmation.

**Comment by turpaultn** [comment]
No most of them are available:
Examples of the two first ones:
https://www.youtube.com/watch?v=KK227gPpRn4
https://www.youtube.com/watch?v=-6p32k2WUCs

**Comment by HarshVardhanSh** [comment]
I couldn't find the videos you mentioned in the dataset. I guess we are talking about different datasets. I am referring to task 4 of the competition. Following are the sample audios from the weak folder of the audio dataset in task 4:
Y-_A4yJmxFdM_30.000_40.000
Y_CZzm6jUxbo_30.000_40.000
Y_KNIJQJ-CHA_30.000_40.000

As written the dataset description, Y-_A4yJmxFdM will be the VideoID for the video associated with the first audio. So I tried using these videoIDs for almost every audio in this folder and for all of them, the youtube says "Video unavailable". 

Let me know where am I failing ?

**Comment by turpaultn** [comment]
The Y at the beginning is audioset convention but shouldn't be put in the ID on youtube.
So youtube IDs: 
Y-_A4yJmxFdM_30.000_40.000 --> -_A4yJmxFdM
Y_CZzm6jUxbo_30.000_40.000 --> _CZzm6jUxbo
Y_KNIJQJ-CHA_30.000_40.000 --> _KNIJQJ-CHA

You would find it in dataset/download_data.py (line 41):
`query_id = filename[1:12]`

Then line 60:
`https://www.youtube.com/watch?v={query_id} `

**Comment by HarshVardhanSh** [comment]
Gotcha! Thanks so much!
