### ISSUE TITLE
task 1: 'ascii' codec can't decode byte 0xd8 in position 0: ordinal not in range(128)

### ISSUE THREAD

**Issue by eshalev4** [DCASE-REPO/dcase2018_baseline#28]
While running task1a in ubuntu bash in windows 10 I am getting: 

>[I] DCASE2018 / Task1A -- Acoustic scene classification
[I]
[I] General information
[I] ========================================
[I]   Parameter set
[I]     Set ID                          : dcase2018_baseline
[I]     Set description                 : DCASE2018 baseline / Development setup
[I]   Application
[I]     Overwrite                       : False
[I]     Dataset                         : TUT-urban-acoustic-scenes-2018-development
[I]     Active folds                    : [1]
[I]
[I]   DONE
[I]
[I] Feature Extraction
[I] ========================================
[I]   DONE       [0:00:00.968335]
[I]
[I] Feature Normalization
[I] ========================================
[I]   Fold [1]
[I]   DONE       [0:00:00.000460]
[I]
[I] Learning
[I] ========================================
[I]   Fold [1]
[I]   DONE       [0:00:00.000478]
[I]
[I] Testing
[I] ========================================
[I]   Fold [1]
 'ascii' codec can't decode byte 0xd8 in position 0: ordinal not in range(128)

Python 2 has no problem with this line. Is the code buile for python 2 or 3?

In python 2 I am getting:

>[E] Uncaught exception  (logging.py:221)
Traceback (most recent call last):
  File "task1a.py", line 1204, in <module>
    sys.exit(main(sys.argv))
  File "task1a.py", line 234, in main
    overwrite=overwrite
  File "task1a.py", line 982, in do_testing
    if keras_model.get_config()[0]['config']['data_format'] == 'channels_first':
KeyError: 0

Is this a versions issue?

**Comment by toni-heittola** [comment]
Task1 baseline is no longer actively maintained as we are currently focusing on baseline systems for DCASE2019 challenge. Baseline systems were developed against versions defined in requirements.txt and newer versions might have breaking changes. The task1 baseline system should work equally well in python 2.x and 3.x. The system was tested in limited fashion on Windows, however, main development is done in Linux. 

First issue is some unicode issue which cannot be tracked down based on current print out. Remove try/except block from main code file (https://github.com/DCASE-REPO/dcase2018_baseline/blob/master/task1/task1a.py#L1195) to see actual error.

Second issue is related Keras version, baseline system has been developed for v2.1.5 and v2.2.3 had breaking change for get_config method (https://github.com/keras-team/keras/releases/tag/2.2.3). In DCASE2019 task 1 baseline this has been solved, see > https://github.com/toni-heittola/dcase2019_task1_baseline/blob/master/task1a.py#L972
