### ISSUE TITLE
Task 4 dataset download

### ISSUE THREAD

**Issue by RicherMans** [DCASE-REPO/dcase2018_baseline#3]
Hey there,
I tried to download the dataset, but some videos are unavailble in my location. Would there be any possiblity to upload the dataset to server directly? (The download overall might be 82Gb, but the extracted 10s parts are probably much smaller)

**Comment by turpaultn** [comment]
Hi, 
First try to relaunch the download (it can reduce the number of missing files), and then send me your missing_files_[dataset].csv produced in the "dataset" folder by [mail](nicolas.turpault@inria.fr).
It is explained in the readme of the dataset folder.

**Comment by turpaultn** [comment]
The problem comes from proxy issue in China. It is a very specific issue and hard to get the exact cause. 
I close it but feel free to reopen it if you face the same issue, we'll take more time investigating it.
